"""remove constraint for repo

Revision ID: 02aa4b78909a
Revises: 9573d1bf4874
Create Date: 2025-09-06 09:27:21.429983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aa4b78909a'
down_revision = '9573d1bf4874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_repo'))
        batch_op.create_index(batch_op.f('ix_post_repo'), ['repo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_repo'))
        batch_op.create_index(batch_op.f('ix_post_repo'), ['repo'], unique=1)

    # ### end Alembic commands ###
