"""increase hashed password length

Revision ID: 112753d54d37
Revises: 02aa4b78909a
Create Date: 2025-09-07 08:42:02.113029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112753d54d37'
down_revision = '02aa4b78909a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
