"""updated twitter threaD...

Revision ID: 34cb72b940c3
Revises: 8faba7e4eb7b
Create Date: 2025-09-12 08:37:54.473493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cb72b940c3'
down_revision = '8faba7e4eb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_thread', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('facebook_post', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_post', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_facebook_post'), ['facebook_post'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_linkedin_post'), ['linkedin_post'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_twitter_thread'), ['twitter_thread'], unique=False)
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_twitter_thread'))
        batch_op.drop_index(batch_op.f('ix_post_linkedin_post'))
        batch_op.drop_index(batch_op.f('ix_post_facebook_post'))
        batch_op.drop_column('linkedin_post')
        batch_op.drop_column('facebook_post')
        batch_op.drop_column('twitter_thread')

    # ### end Alembic commands ###
