"""renamed committed date

Revision ID: 4ed0039bc1b9
Revises: c1d563078f26
Create Date: 2025-09-07 23:41:43.159116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ed0039bc1b9'
down_revision = 'c1d563078f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_committed', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_date_commited'))
        batch_op.create_index(batch_op.f('ix_post_date_committed'), ['date_committed'], unique=False)
        batch_op.drop_column('date_commited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_commited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_date_committed'))
        batch_op.create_index(batch_op.f('ix_post_date_commited'), ['date_commited'], unique=False)
        batch_op.drop_column('date_committed')

    # ### end Alembic commands ###
