"""remove lastname constraint

Revision ID: 9573d1bf4874
Revises: 2261672bcc8f
Create Date: 2025-09-06 08:15:18.544743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9573d1bf4874'
down_revision = '2261672bcc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=360), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_post_repo'), ['repo'], unique=True)
        batch_op.create_index(batch_op.f('ix_post_summary'), ['summary'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_firstname'))
        batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=1)
        batch_op.drop_index(batch_op.f('ix_user_firstname'))
        batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=1)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_summary'))
        batch_op.drop_index(batch_op.f('ix_post_repo'))
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('summary')
        batch_op.drop_column('repo')

    # ### end Alembic commands ###
